# Upset Validation via Wikipedia FIFA Rankings

This notebook web-scrapes Wikipedia pages for each competition and classifies
**upsets** using the five literature-based criteria detailed in the *Upset
classification criteria* section below — betting odds (>= 30 pp), expected
goals (lower-xG team wins), team value (>= 1.5x), FIFA ranking (>= 10, national
cups) and previous league standing (>= 10, leagues) — applied in that order of
preference.  The pure-Wikipedia sections that follow rely on the contextual
fallbacks (FIFA ranking for tournaments, league standing for leagues), while the
preferred odds / xG / value signals are available through the functions in the
criteria section when Transfermarkt / Understat / bookmaker data is supplied.

<!--
 This serves as a cross-validation of the xG-based upset criterion used in
`upset_module.Rmd` and `upset_module_total.Rmd`.
-->

## Competitions covered
1. Bundesliga 23/24 — Bayer Leverkusen games (league; no FIFA rankings; AI-sourced)
2. Africa Cup of Nations 2023 — Wikipedia AFCON groups + knockout
3. FIFA World Cup 2022 — Wikipedia group + knockout pages per group
4. La Liga 20/21 — Barcelona games (league; no FIFA rankings; AI-sourced)
5. Ligue 1 22/23 — PSG games (league; no FIFA rankings; AI-sourced)
6. Ligue 1 21/22 — PSG games (league; no FIFA rankings; AI-sourced)
7. MLS 2023 — Inter Miami 6 matches (league; no FIFA rankings; AI-sourced)
8. UEFA Euro 2024 — Wikipedia groups + knockout
9. UEFA Euro 2020 — Wikipedia groups + knockout
10. UEFA Women's Euro 2025 — Wikipedia groups + knockout
11. UEFA Women's Euro 2022 — Wikipedia groups + knockout
12. FIFA Women's World Cup 2023 — Wikipedia groups + knockout

In [104]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from IPython.display import display

# Minimum FIFA rank difference to classify as upset (can be adjusted)
RANK_DIFF_THRESHOLD = 8

HEADERS = {"User-Agent": "Mozilla/5.0 (research bot; econ_project_2026)"}

def fetch_soup(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=HEADERS, timeout=20)
    resp.raise_for_status()
    time.sleep(0.5)
    return BeautifulSoup(resp.text, "html.parser")

def find_main_article_links(soup: BeautifulSoup) -> list:
    links = []
    for hatnote in soup.find_all(class_="hatnote"):
        for a in hatnote.find_all("a", href=True):
            href = a["href"]
            if href.startswith("/wiki/"):
                links.append("https://en.wikipedia.org" + href)
    return links

def _clean_team_name(raw: str) -> str:
    s = re.sub(r"\s*\[.*?\]", "", raw)   # remove [1], [nb 2], etc.
    s = re.sub(r"[\u2022\u25c6\u2013\-]+\s*$", "", s)
    return s.strip()


# Parses the Wikipedia Teams wikitable to get FIFA rankings.
# Returns DataFrame[team, fifa_rank] using the RIGHTMOST (latest) value.
# Table structure example (WC 2022 Group G):
#   Draw pos | Team | Pot | Confederation | ... | FIFA Rank Mar2022 | Oct2022
#   G1       | Brazil | 1 | CONMEBOL | ... | 1 | 1
#   G2       | Serbia | 3 | UEFA     | ... | 25| 21
# The rightmost numeric column per row = most recent ranking.
def extract_rank_table(soup: BeautifulSoup):
    for tbl in soup.find_all("table", class_="wikitable"):
        tbl_text = tbl.get_text().lower()
        if "rank" not in tbl_text and "fifa" not in tbl_text:
            continue
        all_rows = tbl.find_all("tr")
        header_text, n_hdr = [], 0
        for tr in all_rows:
            if tr.find("th") and not tr.find("td"):
                for th in tr.find_all("th"):
                    header_text.append(th.get_text(strip=True).lower())
                n_hdr += 1
            else:
                break
        has_team = any("team" in h or "country" in h for h in header_text)
        has_rank = any("rank" in h or "fifa" in h for h in header_text)
        if not has_team or not has_rank:
            continue
        rows = []
        for tr in all_rows[n_hdr:]:
            all_cells = tr.find_all(["td", "th"])
            if not all_cells:
                continue
            team = None
            for cell in all_cells:
                a = cell.find("a", href=re.compile(r"^/wiki/[^:]+$"))
                if a:
                    txt = _clean_team_name(cell.get_text(strip=True))
                    if txt and 2 < len(txt) <= 50 and not re.fullmatch(r"[\d\s]+", txt):
                        team = txt
                        break
            if not team:
                continue
            num_vals = [
                int(_clean_team_name(c.get_text(strip=True)))
                for c in all_cells
                if re.fullmatch(r"\d{1,3}",
                                _clean_team_name(c.get_text(strip=True)))
            ]
            if num_vals:
                rows.append({"team": team, "fifa_rank": num_vals[-1]})
        if len(rows) >= 2:
            return pd.DataFrame(rows).drop_duplicates("team").reset_index(drop=True)
    return None

# Scrape data from wikipedia
#
# Strategy 1 (primary): find <td class="fscore"> cells, extract X-Y score,
#   then look in the same <tr> for fhome/faway th elements or th[scope=row].
# Strategy 2 (fallback): scan wikitable rows for a centre X-Y cell flanked
#   by plausible team-name text cells.
def parse_match_results_from_soup(gsoup: BeautifulSoup) -> list:
    results = []
    seen = set()
    score_re = re.compile(r"(\d+)\s*[\u2013\-]\s*(\d+)")

    def _add(home_raw, away_raw, hs, as_, date=""):
        home = _clean_team_name(home_raw)
        away = _clean_team_name(away_raw)
        if not home or not away or home.lower() == away.lower():
            return
        key = tuple(sorted([home.lower(), away.lower()]))
        if key in seen:
            return
        seen.add(key)
        results.append({"home": home, "away": away,
                         "home_score": hs, "away_score": as_, "date": date})

    # Strategy 1: fscore class (football-box template)
    for score_td in gsoup.find_all(["td", "th"], class_=re.compile(r"\bfscore\b", re.I)):
        m = score_re.search(score_td.get_text(strip=True))
        if not m:
            continue
        hs, as_ = int(m.group(1)), int(m.group(2))
        tr = score_td.find_parent("tr")
        if tr is None:
            continue
        home_el = tr.find("th", class_=re.compile(r"\bfhome\b", re.I))
        away_el = tr.find("th", class_=re.compile(r"\bfaway\b", re.I))
        if not home_el or not away_el:
            th_row = tr.find_all("th", attrs={"scope": "row"})
            if len(th_row) >= 2:
                home_el, away_el = th_row[0], th_row[-1]
        if not home_el or not away_el:
            all_th = tr.find_all("th")
            if len(all_th) >= 2:
                home_el, away_el = all_th[0], all_th[-1]
        if home_el and away_el:
            _add(home_el.get_text(strip=True),
                 away_el.get_text(strip=True), hs, as_)

    # Strategy 2: generic score between two name cells
    if not results:
        for tbl in gsoup.find_all("table", class_="wikitable"):
            for tr in tbl.find_all("tr"):
                cells = tr.find_all(["td", "th"])
                for i, cell in enumerate(cells):
                    txt = cell.get_text(strip=True)
                    m = re.fullmatch(r"(\d+)\s*[\u2013\-]\s*(\d+)", txt)
                    if not m or i == 0 or i == len(cells) - 1:
                        continue
                    prev = cells[i - 1].get_text(strip=True)
                    nxt  = cells[i + 1].get_text(strip=True)
                    if (prev and nxt and not prev.isdigit() and not nxt.isdigit()
                            and 3 <= len(prev) <= 40 and 3 <= len(nxt) <= 40):
                        _add(prev, nxt, int(m.group(1)), int(m.group(2)))
    return results

# Name normalization
_ALIASES = {
    "ir iran":            "iran",
    "iran":               "ir iran",
    "korea republic":     "south korea",
    "republic of korea":  "south korea",
    "south korea":        "korea republic",
    "ivory coast":        "cote d'ivoire",
    "cote d'ivoire":      "ivory coast",
    "united states":      "usa",
    "usa":                "united states",
    "north macedonia":    "macedonia",
    "fyr macedonia":      "north macedonia",
    "czech republic":     "czechia",
    "czechia":            "czech republic",
    "turkiye":            "turkey",
    "turkey":             "turkiye",
    "the gambia":         "gambia",
    "dr congo":           "congo dr",
    "dem. rep. congo":    "dr congo",
    "democratic republic of the congo": "dr congo",
}

def _norm(name: str) -> str:
    s = _clean_team_name(name).lower()
    s = re.sub(r"['\u2019\u2018]", "'", s)
    import unicodedata
    s = ''.join(c for c in unicodedata.normalize('NFD', s)
                if unicodedata.category(c) != 'Mn')
    return _ALIASES.get(s, s)

def _find_rank(team: str, rank_map: dict):
    """Exact then normalised lookup in rank_map."""
    if team in rank_map:
        return rank_map[team]
    n = _norm(team)
    for k, v in rank_map.items():
        if _norm(k) == n:
            return v
    return None

def identify_upsets_from_matches(
        matches,
        rank_map,
        threshold=RANK_DIFF_THRESHOLD,
) -> pd.DataFrame:
    """
    Scrapes team names and scores from parsed match dicts, looks up FIFA
    rankings from rank_map (with normalised / alias matching), and returns
    rows where:
      - abs(rank_home - rank_away) >= threshold
      - the lower-ranked team (higher rank number) won outright
    Matches the structure found in Wikipedia group/stage pages:
      Teams table: Draw pos | Team | ... | FIFA Rank Mar | FIFA Rank Latest
      Matches:     <th class=fhome>Team</th><td class=fscore>X-Y</td><th class=faway>
    """
    records = []
    for m in matches:
        home, away = m["home"], m["away"]
        hs, as_ = m.get("home_score", 0), m.get("away_score", 0)
        r_home = _find_rank(home, rank_map)
        r_away = _find_rank(away, rank_map)
        if r_home is None or r_away is None:
            continue
        diff = abs(r_home - r_away)
        if diff < threshold:
            continue
        fav   = home if r_home < r_away else away
        under = away if r_home < r_away else home
        winner = home if hs > as_ else (away if as_ > hs else None)
        if winner and _norm(winner) == _norm(under):
            records.append({
                "date":      m.get("date", ""),
                "home":      home,
                "away":      away,
                "score":     f"{hs}-{as_}",
                "favourite": fav,
                "underdog":  under,
                "fav_rank":  min(r_home, r_away),
                "und_rank":  max(r_home, r_away),
                "rank_diff": diff,
            })
    return pd.DataFrame(records)

print(f"Setup complete. RANK_DIFF_THRESHOLD = {RANK_DIFF_THRESHOLD}")
print("Functions: extract_rank_table, parse_match_results_from_soup,")
print("           identify_upsets_from_matches  (with fuzzy team matching)")

Setup complete. RANK_DIFF_THRESHOLD = 8
Functions: extract_rank_table, parse_match_results_from_soup,
           identify_upsets_from_matches  (with fuzzy team matching)

---
## Upset classification criteria (per specification)

Following the literature (Vincent 2025 — xG; Vicente et al. 2024 — rank gaps;
Ben-Naim et al. 2006 — parity/predictability; betting-odds methodology from
GammaStack / BettorsInsider / BeSoccer), a match is judged an **upset** when a
genuinely weaker team beats a stronger one.  Five characteristics determine which
side is the underdog, each implemented as its own concise function below:

| # | Criterion | Underdog gate | Source | Scope |
|---|-----------|---------------|--------|-------|
| 1 | **Betting odds**     | favourite implied win prob exceeds underdog by **>= 30 pp** | football-data.co.uk / books that consume Transfermarkt+Understat models | all |
| 2 | **Expected goals**   | underdog has **strictly lower xG** and still wins | Understat / StatsBomb | all |
| 3 | **Team value**       | favourite squad+manager+stadium value **>= 1.5x** underdog | Transfermarkt | all |
| 4 | **FIFA ranking**     | rank-number gap **>= 10** | Wikipedia / Transfermarkt | national tournaments |
| 5 | **Prev. league standing** | finishing-position gap **>= 10** | Wikipedia / Transfermarkt | domestic leagues |

**Preference order:** betting odds -> expected goals -> team value, because
bookmakers, Transfermarkt and Understat already fold advanced analytics into
those numbers.  FIFA ranking (national cups) and previous league standing
(leagues) are the contextual fallbacks used when the preferred signals are
unavailable — which is the case for the pure-Wikipedia scraping in the sections
that follow.

In [105]:
# Criterion 1 -- Betting odds
# Upset when win probability of the underdog exceeds >= 30 percentage points,
# and the underdog wins.

def implied_prob(decimal_odds):
    """Decimal odds -> implied win probability (1 / odds)."""
    try:
        o = float(decimal_odds)
        return 1.0 / o if o > 0 else None
    except (TypeError, ValueError):
        return None

def devig_two_way(p_a, p_b):
    """Normalise two implied probabilities so they sum to 1 (removes the book margin)."""
    if p_a is None or p_b is None:
        return p_a, p_b
    s = p_a + p_b
    return (p_a / s, p_b / s) if s > 0 else (p_a, p_b)

def classify_by_odds(home, away, odds_home, odds_away, winner, diff_threshold=0.30):
    """Betting-odds upset signal. Returns a dict or None if odds are missing."""
    p_home, p_away = devig_two_way(implied_prob(odds_home), implied_prob(odds_away))
    if p_home is None or p_away is None or winner is None:
        return None
    fav, dog = (home, away) if p_home >= p_away else (away, home)
    p_fav, p_dog = max(p_home, p_away), min(p_home, p_away)
    diff = p_fav - p_dog
    return {
        "criterion": "betting_odds", "favourite": fav, "underdog": dog,
        "fav_prob": round(p_fav, 3), "dog_prob": round(p_dog, 3),
        "magnitude": round(diff, 3), "meets_gate": diff >= diff_threshold,
        "is_upset": diff >= diff_threshold and _norm(winner) == _norm(dog),
    }

def load_league_odds_footballdata(country_code, season_start):
    """Closing bookmaker odds for a domestic-league season from football-data.co.uk.
    country_code e.g. 'E0','SP1','F1','D1'. Mirrors load_odds() in identify_upsets.r."""
    url = (f"https://www.football-data.co.uk/mmz4281/"
           f"{season_start % 100:02d}{(season_start + 1) % 100:02d}/{country_code}.csv")
    try:
        df = pd.read_csv(url)
    except Exception as e:
        print("  odds unavailable:", e)
        return pd.DataFrame()
    h = df["PSCH"] if "PSCH" in df else df.get("B365H")   # Pinnacle closing, B365 fallback
    a = df["PSCA"] if "PSCA" in df else df.get("B365A")
    return pd.DataFrame({
        "home": df.get("HomeTeam"), "away": df.get("AwayTeam"),
        "odds_home": pd.to_numeric(h, errors="coerce"),
        "odds_away": pd.to_numeric(a, errors="coerce"),
    })

print("Criterion 1 ready: implied_prob, devig_two_way, classify_by_odds, load_league_odds_footballdata")

Criterion 1 ready: implied_prob, devig_two_way, classify_by_odds, load_league_odds_footballdata

In [106]:
# Criterion 2 -- Expected goals
# The underdog is the side with lower expected goals (xG)
import json, os

def classify_by_xg(home, away, xg_home, xg_away, winner):
    """Expected-goals upset signal. Returns a dict or None if xG is missing/tied."""
    if xg_home is None or xg_away is None or winner is None or xg_home == xg_away:
        return None
    fav, dog = (home, away) if xg_home > xg_away else (away, home)
    return {
        "criterion": "expected_goals", "favourite": fav, "underdog": dog,
        "xg_fav": round(max(xg_home, xg_away), 3), "xg_dog": round(min(xg_home, xg_away), 3),
        "magnitude": round(abs(xg_home - xg_away), 3), "meets_gate": True,
        "is_upset": _norm(winner) == _norm(dog),
    }

EVENTS_DIR = os.path.join("..", "open-data", "data", "events")

def compute_statsbomb_xg(match_id, events_dir=EVENTS_DIR):
    """Sum StatsBomb shot xG per team from the local open-data events JSON
    (open-data/data/events/{match_id}.json).  Returns {team: total_xg}.
    Understat provides equivalent shot xG for domestic-league fixtures."""
    path = os.path.join(events_dir, f"{match_id}.json")
    try:
        with open(path) as fh:
            events = json.load(fh)
    except Exception as e:
        print("  xG events unavailable:", e)
        return {}
    totals = {}
    for ev in events:
        if ev.get("type", {}).get("name") == "Shot":
            team = ev.get("team", {}).get("name")
            xg = ev.get("shot", {}).get("statsbomb_xg", 0.0) or 0.0
            if team is not None:
                totals[team] = totals.get(team, 0.0) + xg
    return totals

print("Criterion 2 ready: classify_by_xg, compute_statsbomb_xg (Understat/StatsBomb)")

Criterion 2 ready: classify_by_xg, compute_statsbomb_xg (Understat/StatsBomb)

In [107]:
# Criterion 3 — Team value
# Team value aggregates the three components named in the spec — player (squad
# market value), manager (market value) and stadium (capacity as a value proxy).
# Favourite = higher value; an upset requires value_fav / value_dog >= 1.5.

def team_total_value(squad_value_eur, manager_value_eur=0.0, stadium_capacity=0):
    """Combine player + manager + stadium value (all Transfermarkt-sourced)."""
    return (squad_value_eur or 0.0) + (manager_value_eur or 0.0) + 1000.0 * (stadium_capacity or 0)

def classify_by_value(home, away, value_home, value_away, winner, ratio_threshold=1.5):
    """Squad-value upset signal. Returns a dict or None if values are missing."""
    if not value_home or not value_away or winner is None:
        return None
    fav, dog = (home, away) if value_home >= value_away else (away, home)
    v_fav, v_dog = max(value_home, value_away), min(value_home, value_away)
    ratio = v_fav / v_dog if v_dog else float("inf")
    return {
        "criterion": "team_value", "favourite": fav, "underdog": dog,
        "value_fav": v_fav, "value_dog": v_dog,
        "magnitude": round(ratio, 2), "meets_gate": ratio >= ratio_threshold,
        "is_upset": ratio >= ratio_threshold and _norm(winner) == _norm(dog),
    }

def load_transfermarkt_squad_value(team_name):
    """Best-effort scrape of a club/national team's total squad market value (EUR)
    from Transfermarkt search results.  Transfermarkt markup changes often and may
    return 403 from a bot UA; supply values manually (value_map) if this fails."""
    url = "https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche"
    try:
        r = requests.get(url, params={"query": team_name}, headers=HEADERS, timeout=20)
        soup = BeautifulSoup(r.text, "html.parser")
        cell = soup.find(string=re.compile(r"[€€]\s?\d"))
        if not cell:
            return None
        txt = cell.strip().replace("€", "").replace("€", "").strip()
        mult = 1e6 if "m" in txt.lower() else (1e9 if "bn" in txt.lower() else 1.0)
        num = re.sub(r"[^\d.]", "", txt)
        return float(num) * mult if num else None
    except Exception as e:
        print("  Transfermarkt unavailable:", e)
        return None

print("Criterion 3 ready: team_total_value, classify_by_value, load_transfermarkt_squad_value")

Criterion 3 ready: team_total_value, classify_by_value, load_transfermarkt_squad_value

In [108]:
# Criterion 4 -- FIFA ranking
# Lower rank number = stronger team.  Upset requires a rank gap >= 10 and the
# lower-ranked (higher-number) team to win.  Rankings come from the Wikipedia
# group-page tables parsed by extract_rank_table() (also published by Transfermarkt).

def classify_by_fifa_rank(home, away, rank_home, rank_away, winner, diff_threshold=10):
    """FIFA-ranking upset signal. Returns a dict or None if ranks are missing."""
    if rank_home is None or rank_away is None or winner is None:
        return None
    fav, dog = (home, away) if rank_home < rank_away else (away, home)
    diff = abs(rank_home - rank_away)
    return {
        "criterion": "fifa_rank", "favourite": fav, "underdog": dog,
        "fav_rank": min(rank_home, rank_away), "dog_rank": max(rank_home, rank_away),
        "magnitude": diff, "meets_gate": diff >= diff_threshold,
        "is_upset": diff >= diff_threshold and _norm(winner) == _norm(dog),
    }

print("Criterion 4 ready: classify_by_fifa_rank (reuses extract_rank_table / _find_rank)")

Criterion 4 ready: classify_by_fifa_rank (reuses extract_rank_table / _find_rank)

In [109]:
# Criterion 5 -- Previous league standing
# Lower finishing position number = stronger team.  Upset requires a standing gap
# >= 10 places and the lower-placed team to win.  Positions come from the
# previous-season Wikipedia league table (or Transfermarkt).

def classify_by_league_standing(home, away, pos_home, pos_away, winner, diff_threshold=10):
    """League-standing upset signal. Returns a dict or None if positions are missing."""
    if pos_home is None or pos_away is None or winner is None:
        return None
    fav, dog = (home, away) if pos_home < pos_away else (away, home)
    diff = abs(pos_home - pos_away)
    return {
        "criterion": "league_standing", "favourite": fav, "underdog": dog,
        "fav_pos": min(pos_home, pos_away), "dog_pos": max(pos_home, pos_away),
        "magnitude": diff, "meets_gate": diff >= diff_threshold,
        "is_upset": diff >= diff_threshold and _norm(winner) == _norm(dog),
    }

def load_prev_season_table_wikipedia(season_url, table_keyword="position"):
    """Return {team: finishing_position} from a Wikipedia league-season page's
    final standings wikitable.  Falls back gracefully if the table is not found."""
    try:
        soup = fetch_soup(season_url)
    except Exception as e:
        print("  league table unavailable:", e)
        return {}
    for tbl in soup.find_all("table", class_="wikitable"):
        head = tbl.get_text().lower()
        if "pos" not in head and "pld" not in head:
            continue
        table = {}
        for i, tr in enumerate(tbl.find_all("tr")):
            link = tr.find("a", href=re.compile(r"^/wiki/[^:]+$"))
            num = tr.find(["th", "td"])
            if link and num:
                pos = re.sub(r"\D", "", num.get_text(strip=True))
                if pos:
                    table[_clean_team_name(link.get_text(strip=True))] = int(pos)
        if len(table) >= 2:
            return table
    return {}

print("Criterion 5 ready: classify_by_league_standing, load_prev_season_table_wikipedia")

Criterion 5 ready: classify_by_league_standing, load_prev_season_table_wikipedia

In [110]:
# Combined classifier
# 1 betting odds -> 2 expected goals -> 3 team value  (preferred analytics),
# then the context fallback: 4 FIFA rank (national) or 5 league standing (league).
# The first criterion that has data decides the verdict.

def classify_upset(home, away, winner, *, is_national=True,
                   odds_home=None, odds_away=None,
                   xg_home=None, xg_away=None,
                   value_home=None, value_away=None,
                   rank_home=None, rank_away=None,
                   pos_home=None, pos_away=None,
                   odds_threshold=0.30, value_ratio=1.5,
                   rank_threshold=10, standing_threshold=10):
    """Return the decision dict from the first available criterion (with a 'used'
    key naming it), or None when no criterion has data."""
    ladder = [
        classify_by_odds(home, away, odds_home, odds_away, winner, odds_threshold),
        classify_by_xg(home, away, xg_home, xg_away, winner),
        classify_by_value(home, away, value_home, value_away, winner, value_ratio),
    ]
    fallback = (classify_by_fifa_rank(home, away, rank_home, rank_away, winner, rank_threshold)
                if is_national else
                classify_by_league_standing(home, away, pos_home, pos_away, winner, standing_threshold))
    for sig in ladder + [fallback]:
        if sig is not None:
            sig = dict(sig)
            sig["used"] = sig["criterion"]
            return sig
    return None

def classify_matches(matches, *, is_national=True, rank_map=None, pos_map=None,
                     value_map=None, xg_map=None, odds_map=None, **thresholds):
    """Run classify_upset over a list of match dicts and return only the upsets as
    a tidy DataFrame.  Per-team metrics may be supplied via *_map dicts (looked up
    with the fuzzy _find_rank matcher) or inline odds_home/odds_away/xg_* fields."""
    def look(d, t):
        return _find_rank(t, d) if d else None
    rows = []
    for m in matches:
        home, away = m["home"], m["away"]
        hs, as_ = m.get("home_score", 0), m.get("away_score", 0)
        winner = home if hs > as_ else (away if as_ > hs else None)
        om = (odds_map or {}).get(tuple(sorted([home, away])), {})
        sig = classify_upset(
            home, away, winner, is_national=is_national,
            odds_home=m.get("odds_home", om.get("odds_home")),
            odds_away=m.get("odds_away", om.get("odds_away")),
            xg_home=m.get("xg_home", look(xg_map, home)),
            xg_away=m.get("xg_away", look(xg_map, away)),
            value_home=look(value_map, home), value_away=look(value_map, away),
            rank_home=look(rank_map, home), rank_away=look(rank_map, away),
            pos_home=look(pos_map, home),  pos_away=look(pos_map, away),
            **thresholds)
        if sig and sig["is_upset"]:
            rows.append({"date": m.get("date", ""), "home": home, "away": away,
                         "score": f"{hs}-{as_}", "criterion": sig["used"],
                         "favourite": sig["favourite"], "underdog": sig["underdog"],
                         "magnitude": sig["magnitude"]})
    return pd.DataFrame(rows)

print("Combined classifier ready: classify_upset (preference order), classify_matches")

Combined classifier ready: classify_upset (preference order), classify_matches

### Demonstration

The cell below shows all five criteria agreeing on the classic 2022 upset
Argentina 1-2 Saudi Arabia, and the combined classifier selecting the
preferred (betting-odds) verdict.  Brazil 2-0 Serbia is included as a non-upset
control.

In [111]:
# Worked example — every criterion on Argentina 1-2 Saudi Arabia (2022 WC)
arg_sau = dict(home="Argentina", away="Saudi Arabia", winner="Saudi Arabia")
print("odds   :", classify_by_odds("Argentina", "Saudi Arabia", 1.16, 15.0, "Saudi Arabia"))
print("xG     :", classify_by_xg("Argentina", "Saudi Arabia", 2.30, 0.15, "Saudi Arabia"))
print("value  :", classify_by_value("Argentina", "Saudi Arabia", 875e6, 18e6, "Saudi Arabia"))
print("rank   :", classify_by_fifa_rank("Argentina", "Saudi Arabia", 3, 51, "Saudi Arabia"))
print("chosen :", classify_upset("Argentina", "Saudi Arabia", "Saudi Arabia",
                                 odds_home=1.16, odds_away=15.0,
                                 xg_home=2.30, xg_away=0.15,
                                 value_home=875e6, value_away=18e6,
                                 rank_home=3, rank_away=51)["used"])

# Vectorised over a small mixed batch (rank fallback + inline odds/xg)
demo_matches = [
    {"home": "Argentina", "away": "Saudi Arabia", "home_score": 1, "away_score": 2,
     "odds_home": 1.16, "odds_away": 15.0, "xg_home": 2.30, "xg_away": 0.15},
    {"home": "Brazil",    "away": "Serbia",       "home_score": 2, "away_score": 0,
     "odds_home": 1.30, "odds_away": 9.0,  "xg_home": 2.10, "xg_away": 0.40},
]
demo_rank_map = {"Argentina": 3, "Saudi Arabia": 51, "Brazil": 1, "Serbia": 21}
display(classify_matches(demo_matches, is_national=True, rank_map=demo_rank_map))

odds   : {'criterion': 'betting_odds', 'favourite': 'Argentina', 'underdog': 'Saudi Arabia', 'fav_prob': 0.928, 'dog_prob': 0.072, 'magnitude': 0.856, 'meets_gate': True, 'is_upset': True}
xG     : {'criterion': 'expected_goals', 'favourite': 'Argentina', 'underdog': 'Saudi Arabia', 'xg_fav': 2.3, 'xg_dog': 0.15, 'magnitude': 2.15, 'meets_gate': True, 'is_upset': True}
value  : {'criterion': 'team_value', 'favourite': 'Argentina', 'underdog': 'Saudi Arabia', 'value_fav': 875000000.0, 'value_dog': 18000000.0, 'magnitude': 48.61, 'meets_gate': True, 'is_upset': True}
rank   : {'criterion': 'fifa_rank', 'favourite': 'Argentina', 'underdog': 'Saudi Arabia', 'fav_rank': 3, 'dog_rank': 51, 'magnitude': 48, 'meets_gate': True, 'is_upset': True}
chosen : betting_odds

,date,home,away,score,criterion,favourite,underdog,magnitude
0,,Argentina,Saudi Arabia,1-2,betting_odds,Argentina,Saudi Arabia,0.856

In [112]:
# Control-match identifier (copied verbatim from control_online.ipynb).
# CONTROL = the favourite (better-ranked) team won; mirror of the upset gate.
def identify_controls_from_matches(
        matches,
        rank_map,
        threshold=RANK_DIFF_THRESHOLD,
) -> pd.DataFrame:
    """
    CONTROL matches = the EXPECTED outcome.  This is the mirror image of
    identify_upsets_from_matches: same mismatch gate, opposite winner.

    Returns rows where:
      - abs(rank_home - rank_away) >= threshold  (a genuine mismatch), AND
      - the FAVOURITE (lower rank number = higher-ranked team) won outright.

    Draws are excluded (a control requires the favourite to actually win).
    Columns mirror the upset frame so the two can be concatenated / compared.
    """
    records = []
    for m in matches:
        home, away = m["home"], m["away"]
        hs, as_ = m.get("home_score", 0), m.get("away_score", 0)
        r_home = _find_rank(home, rank_map)
        r_away = _find_rank(away, rank_map)
        if r_home is None or r_away is None:
            continue
        diff = abs(r_home - r_away)
        if diff < threshold:
            continue
        fav   = home if r_home < r_away else away
        under = away if r_home < r_away else home
        winner = home if hs > as_ else (away if as_ > hs else None)
        if winner and _norm(winner) == _norm(fav):
            records.append({
                "date":      m.get("date", ""),
                "home":      home,
                "away":      away,
                "score":     f"{hs}-{as_}",
                "favourite": fav,
                "underdog":  under,
                "fav_rank":  min(r_home, r_away),
                "und_rank":  max(r_home, r_away),
                "rank_diff": diff,
            })
    return pd.DataFrame(records)

---
## Section 1 — Bundesliga 2023/24 (Bayer Leverkusen)

Domestic league competitions do not have FIFA national-team rankings.
Upset classification is based on pre-match Bundesliga table position
(higher-placed team = favourite).  No upsets found so try and find games sourced from Google AI overview /
Claude because no structured Wikipedia ranking table exists for club leagues.

In [113]:
# ── Section 1: Bundesliga 2023/24 — Bayer Leverkusen ─────────────────────────
# Source: AI overview / Claude hardcoded — no FIFA ranking tables for club leagues.
# Upset criterion: Leverkusen (table leaders) lost points vs lower-table opponents
# where the opponent was ranked >= 10 places below in the Bundesliga table.
#
# Leverkusen's 2023-24 unbeaten record means they collected no genuine upsets
# in their own matches as underdogs.  The 'upset' frame here records matches
# where a significantly lower-placed club took points from Leverkusen.
#
# Hardcoded from Google AI overview / Claude (no Wikipedia ranking table):
# Leverkusen drew with Dortmund (rank ~3) on 2024-02-10 → not an upset (close ranks).
# No match meets the >=10-place rank-diff criterion for Leverkusen in 23/24.

bundesliga_leverkusen_upsets = []  # No qualifying upsets under rank-diff >= 10

print("Bundesliga 2023/24 — Bayer Leverkusen: 0 upsets (rank-diff criterion).")
print("(League standings used; no FIFA ranking applicable for club competitions.)")

Bundesliga 2023/24 — Bayer Leverkusen: 0 upsets (rank-diff criterion).
(League standings used; no FIFA ranking applicable for club competitions.)

In [114]:
# -- Section 1: Bundesliga 2023/24 -- Bayer Leverkusen --------------------------
# Hardcoded from Google AI overview / Claude (no FIFA ranking for club leagues).
# Bundesliga 2023/24 final table (position used as rank proxy):
#   1 Leverkusen, 2 Stuttgart, 3 Bayern, 4 Leipzig, 5 Dortmund, 6 Frankfurt,
#   7 Hoffenheim, 8 Heidenheim, 9 Werder Bremen, 10 Freiburg, 11 Augsburg,
#   12 Wolfsburg, 13 Mainz, 14 Monchengladbach, 15 Union Berlin, 16 Bochum,
#   17 Koln, 18 Darmstadt
#
# Control = Leverkusen (rank 1) beating a team ranked >= 11 (diff >= 10).

bundesliga_rank_map = {
    "Bayer Leverkusen": 1, "Stuttgart": 2, "Bayern Munich": 3, "RB Leipzig": 4,
    "Borussia Dortmund": 5, "Eintracht Frankfurt": 6, "Hoffenheim": 7,
    "Heidenheim": 8, "Werder Bremen": 9, "Freiburg": 10, "Augsburg": 11,
    "Wolfsburg": 12, "Mainz": 13, "Borussia Monchengladbach": 14,
    "Union Berlin": 15, "Bochum": 16, "Koln": 17, "Darmstadt": 18,
}

# Leverkusen's wins over much-lower-placed sides (AI-sourced hardcoded):
leverkusen_matches = [
    {"home": "Bayer Leverkusen", "away": "Darmstadt",    "home_score": 4, "away_score": 0, "date": "2023-09-23"},
    {"home": "Bochum",           "away": "Bayer Leverkusen", "home_score": 1, "away_score": 4, "date": "2023-12-03"},
    {"home": "Bayer Leverkusen", "away": "Koln",         "home_score": 3, "away_score": 0, "date": "2024-01-27"},
    {"home": "Bayer Leverkusen", "away": "Augsburg",     "home_score": 1, "away_score": 0, "date": "2024-04-14"},
    {"home": "Wolfsburg",        "away": "Bayer Leverkusen", "home_score": 0, "away_score": 2, "date": "2024-03-16"},
    {"home": "Mainz",            "away": "Bayer Leverkusen", "home_score": 1, "away_score": 2, "date": "2024-04-27"},
]

bundesliga_controls = identify_controls_from_matches(
    leverkusen_matches, bundesliga_rank_map, RANK_DIFF_THRESHOLD
)
print(f"Bundesliga 23/24 Leverkusen controls (rank diff >= {RANK_DIFF_THRESHOLD}): {len(bundesliga_controls)}")
display(bundesliga_controls)

Bundesliga 23/24 Leverkusen controls (rank diff >= 8): 6

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,2023-09-23,Bayer Leverkusen,Darmstadt,4-0,Bayer Leverkusen,Darmstadt,1,18,17
1,2023-12-03,Bochum,Bayer Leverkusen,1-4,Bayer Leverkusen,Bochum,1,16,15
2,2024-01-27,Bayer Leverkusen,Koln,3-0,Bayer Leverkusen,Koln,1,17,16
3,2024-04-14,Bayer Leverkusen,Augsburg,1-0,Bayer Leverkusen,Augsburg,1,11,10
4,2024-03-16,Wolfsburg,Bayer Leverkusen,0-2,Bayer Leverkusen,Wolfsburg,1,12,11
5,2024-04-27,Mainz,Bayer Leverkusen,1-2,Bayer Leverkusen,Mainz,1,13,12

---
## Section 2 — Africa Cup of Nations 2023

Wikipedia main article: [2023 Africa Cup of Nations](https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations)

Sub-pages per group (Main article: 2023 Africa Cup of Nations Group A, etc.) and
knockout stage are scraped for FIFA ranking tables.

In [115]:
# ── Section 2: Africa Cup of Nations 2023 ────────────────────────────────────
AFCON_MAIN = "https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations"

soup_afcon = fetch_soup(AFCON_MAIN)
all_afcon_links = find_main_article_links(soup_afcon)
afcon_stage_pat = re.compile(r"2023_Africa_Cup_of_Nations_(Group_[A-F]|knockout_stage|final)$", re.I)
group_links = [l for l in all_afcon_links if afcon_stage_pat.search(l)]
print("AFCON 2023 stage pages found:", len(group_links))
for lnk in group_links:
    print(" ", lnk)

AFCON 2023 stage pages found: 8
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_Group_A
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_Group_B
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_Group_C
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_Group_D
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_Group_E
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_Group_F
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_knockout_stage
  https://en.wikipedia.org/wiki/2023_Africa_Cup_of_Nations_final

In [116]:
# Scrape FIFA rankings and match results from each AFCON stage page
afcon_rank_map = {}
afcon_matches  = []

for link in group_links:
    try:
        gsoup = fetch_soup(link)
        rank_df = extract_rank_table(gsoup)
        if rank_df is not None:
            for _, row in rank_df.iterrows():
                afcon_rank_map[row["team"]] = row["fifa_rank"]
        afcon_matches.extend(parse_match_results_from_soup(gsoup))
    except Exception as e:
        print(f"  Error scraping {link}: {e}")

print(f"AFCON rank map: {len(afcon_rank_map)} teams")
print(dict(list(afcon_rank_map.items())[:8]), "...")
print(f"AFCON matches found: {len(afcon_matches)}")

AFCON rank map: 24 teams
{'Ivory Coast': 49, 'Nigeria': 42, 'Equatorial Guinea': 88, 'Guinea-Bissau': 103, 'Egypt': 33, 'Ghana': 61, 'Cape Verde': 73, 'Mozambique': 111} ...
AFCON matches found: 53

In [117]:
afcon_upsets = identify_upsets_from_matches(afcon_matches, afcon_rank_map, RANK_DIFF_THRESHOLD)
print(f"AFCON 2023 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(afcon_upsets)}")
display(afcon_upsets)

AFCON 2023 upsets (rank diff >= 8): 7

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Equatorial Guinea,Ivory Coast,4-0,Ivory Coast,Equatorial Guinea,49,88,39
1,,Ghana,Cape Verde,1-2,Ghana,Cape Verde,61,73,12
2,,Mauritania,Angola,2-3,Mauritania,Angola,105,117,12
3,,Angola,Burkina Faso,2-0,Burkina Faso,Angola,58,117,59
4,,Mauritania,Algeria,1-0,Algeria,Mauritania,30,105,75
5,,Tunisia,Namibia,0-1,Tunisia,Namibia,28,115,87
6,,Morocco,South Africa,0-2,Morocco,South Africa,13,66,53

In [118]:
afcon_controls = identify_controls_from_matches(afcon_matches, afcon_rank_map, RANK_DIFF_THRESHOLD)
print(f"AFCON 2023 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(afcon_controls)}")
display(afcon_controls)

AFCON 2023 control matches (favourite won, rank diff >= 8): 19

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Ivory Coast,Guinea-Bissau,2-0,Ivory Coast,Guinea-Bissau,49,103,54
1,,Equatorial Guinea,Guinea-Bissau,4-2,Equatorial Guinea,Guinea-Bissau,88,103,15
2,,Guinea-Bissau,Nigeria,0-1,Nigeria,Guinea-Bissau,42,103,61
3,,Cape Verde,Mozambique,3-0,Cape Verde,Mozambique,73,111,38
4,,Senegal,Gambia,3-0,Senegal,Gambia,20,126,106
5,,Senegal,Cameroon,3-1,Senegal,Cameroon,20,46,26
6,,Guinea,Gambia,1-0,Guinea,Gambia,80,126,46
7,,Guinea,Senegal,0-2,Senegal,Guinea,20,80,60
8,,Gambia,Cameroon,2-3,Cameroon,Gambia,46,126,80
9,,Burkina Faso,Mauritania,1-0,Burkina Faso,Mauritania,58,105,47
10,,Mali,South Africa,2-0,Mali,South Africa,51,66,15
11,,South Africa,Namibia,4-0,South Africa,Namibia,66,115,49
12,,Morocco,Tanzania,3-0,Morocco,Tanzania,13,121,108
13,,Zambia,Morocco,0-1,Morocco,Zambia,13,84,71
14,,Equatorial Guinea,Guinea,0-1,Guinea,Equatorial Guinea,80,88,8
15,,Cape Verde,Mauritania,1-0,Cape Verde,Mauritania,73,105,32
16,,Nigeria,Angola,1-0,Nigeria,Angola,42,117,75
17,,DR Congo,Guinea,3-1,DR Congo,Guinea,67,80,13
18,,Ivory Coast,DR Congo,1-0,Ivory Coast,DR Congo,49,67,18

---
## Section 3 — FIFA World Cup 2022

Wikipedia main article: [2022 FIFA World Cup](https://en.wikipedia.org/wiki/2022_FIFA_World_Cup)

Each group page (Main article: 2022 FIFA World Cup Group A … H) and the
knockout stage page contain FIFA ranking tables.

In [119]:
# ── Section 3: FIFA World Cup 2022 ───────────────────────────────────────────
WC2022_MAIN = "https://en.wikipedia.org/wiki/2022_FIFA_World_Cup"

soup_wc = fetch_soup(WC2022_MAIN)
wc_links = find_main_article_links(soup_wc)
print("WC 2022 sub-pages found:", len(wc_links))
for lnk in wc_links:
    print(" ", lnk)

WC 2022 sub-pages found: 37
  https://en.wikipedia.org/wiki/2022_World_Cup_(disambiguation)
  https://en.wikipedia.org/wiki/FIFA_22
  https://en.wikipedia.org/wiki/2018_and_2022_FIFA_World_Cup_bids
  https://en.wikipedia.org/wiki/Qatar_2022_FIFA_World_Cup_bid
  https://en.wikipedia.org/wiki/List_of_football_stadiums_in_Qatar
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_qualification
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_squads
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_seeding
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_officials
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_opening_ceremony
  https://en.wikipedia.org/wiki/Arabia_Standard_Time
  https://en.wikipedia.org/wiki/UTC%2B03:00
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_A
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_B
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_C
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_D
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_E
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_F
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_G
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_H
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_knockout_stage
  https://en.wikipedia.org/wiki/Arabia_Standard_Time
  https://en.wikipedia.org/wiki/UTC%2B03:00
  https://en.wikipedia.org/wiki/Battle_of_Lusail
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_final
  https://en.wikipedia.org/wiki/FIFA_World_Cup_records_and_statistics
  https://en.wikipedia.org/wiki/FIFA_World_Cup_video_games
  https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_broadcasting_rights
  https://en.wikipedia.org/wiki/La%27eeb
  https://en.wikipedia.org/wiki/Adidas_Al_Rihla
  https://en.wikipedia.org/wiki/FIFA_World_Cup_Qatar_2022_Official_Soundtrack
  https://en.wikipedia.org/wiki/List_of_FIFA_World_Cup_songs_and_anthems
  https://en.wikipedia.org/wiki/List_of_2022_FIFA_World_Cup_controversies
  https://en.wikipedia.org/wiki/Human_rights_issues_involving_the_2022_FIFA_World_Cup#Migrant_workers
  https://en.wikipedia.org/wiki/Garcia_Report
  https://en.wikipedia.org/wiki/International_sporting_sanctions_during_the_Russian_invasion_of_Ukraine
  https://en.wikipedia.org/wiki/LGBTQ_issues_at_the_2022_FIFA_World_Cup

In [120]:
# Filter to group (A–H) and knockout stage sub-pages only
group_pattern   = re.compile(r"2022_FIFA_World_Cup_Group_[A-H]$")
knockout_pattern = re.compile(r"2022_FIFA_World_Cup_knockout_stage$")

wc_stage_links = [lnk for lnk in wc_links
                  if group_pattern.search(lnk) or knockout_pattern.search(lnk)]
print("Filtered stage pages:", wc_stage_links)

wc_rank_map = {}
wc_matches  = []

for link in wc_stage_links:
    try:
        gsoup = fetch_soup(link)
        rank_df = extract_rank_table(gsoup)
        if rank_df is not None:
            for _, row in rank_df.iterrows():
                wc_rank_map[row["team"]] = row["fifa_rank"]
        wc_matches.extend(parse_match_results_from_soup(gsoup))
    except Exception as e:
        print(f"  Error scraping {link}: {e}")

print(f"WC 2022 rank map: {len(wc_rank_map)} teams")
print(f"WC 2022 matches found: {len(wc_matches)}")

Filtered stage pages: ['https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_A', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_B', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_C', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_D', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_E', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_F', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_G', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_Group_H', 'https://en.wikipedia.org/wiki/2022_FIFA_World_Cup_knockout_stage']
WC 2022 rank map: 32 teams
WC 2022 matches found: 64

In [121]:
wc_upsets = identify_upsets_from_matches(wc_matches, wc_rank_map, RANK_DIFF_THRESHOLD)
print(f"WC 2022 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(wc_upsets)}")
display(wc_upsets)

WC 2022 upsets (rank diff >= 8): 11

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Argentina,Saudi Arabia,1-2,Argentina,Saudi Arabia,3,51,48
1,,Tunisia,Australia,0-1,Tunisia,Australia,30,38,8
2,,Australia,Denmark,1-0,Denmark,Australia,10,38,28
3,,Tunisia,France,1-0,France,Tunisia,4,30,26
4,,Germany,Japan,1-2,Germany,Japan,11,24,13
5,,Japan,Spain,2-1,Spain,Japan,7,24,17
6,,Belgium,Morocco,0-2,Belgium,Morocco,2,22,20
7,,Cameroon,Brazil,1-0,Brazil,Cameroon,1,43,42
8,,South Korea,Ghana,2-3,South Korea,Ghana,28,61,33
9,,South Korea,Portugal,2-1,Portugal,South Korea,9,28,19
10,,Morocco,Portugal,1-0,Portugal,Morocco,9,22,13

In [122]:
wc_controls = identify_controls_from_matches(wc_matches, wc_rank_map, RANK_DIFF_THRESHOLD)
print(f"WC 2022 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(wc_controls)}")
display(wc_controls)

WC 2022 control matches (favourite won, rank diff >= 8): 29

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Senegal,Netherlands,0-2,Netherlands,Senegal,8,18,10
1,,Qatar,Senegal,1-3,Senegal,Qatar,18,50,32
2,,Ecuador,Senegal,1-2,Senegal,Ecuador,18,44,26
3,,Netherlands,Qatar,2-0,Netherlands,Qatar,8,50,42
4,,England,Iran,6-2,England,Iran,5,20,15
5,,Wales,England,0-3,England,Wales,5,19,14
6,,Poland,Saudi Arabia,2-0,Poland,Saudi Arabia,26,51,25
7,,Argentina,Mexico,2-0,Argentina,Mexico,3,13,10
8,,Poland,Argentina,0-2,Argentina,Poland,3,26,23
9,,Saudi Arabia,Mexico,1-2,Mexico,Saudi Arabia,13,51,38
10,,France,Australia,4-1,France,Australia,4,38,34
11,,Spain,Costa Rica,7-0,Spain,Costa Rica,7,31,24
12,,Costa Rica,Germany,2-4,Germany,Costa Rica,11,31,20
13,,Belgium,Canada,1-0,Belgium,Canada,2,41,39
14,,Croatia,Canada,4-1,Croatia,Canada,12,41,29
15,,Canada,Morocco,1-2,Morocco,Canada,22,41,19
16,,Switzerland,Cameroon,1-0,Switzerland,Cameroon,15,43,28
17,,Brazil,Serbia,2-0,Brazil,Serbia,1,21,20
18,,Brazil,Switzerland,1-0,Brazil,Switzerland,1,15,14
19,,Portugal,Ghana,3-2,Portugal,Ghana,9,61,52
20,,Ghana,Uruguay,0-2,Uruguay,Ghana,14,61,47
21,,Netherlands,United States,3-1,Netherlands,United States,8,16,8
22,,Argentina,Australia,2-1,Argentina,Australia,3,38,35
23,,France,Poland,3-1,France,Poland,4,26,22
24,,England,Senegal,3-0,England,Senegal,5,18,13
25,,Brazil,South Korea,4-1,Brazil,South Korea,1,28,27
26,,Argentina,Croatia,3-0,Argentina,Croatia,3,12,9
27,,France,Morocco,2-0,France,Morocco,4,22,18
28,,Croatia,Morocco,2-1,Croatia,Morocco,12,22,10

---
## Section 4 — La Liga 2020/21 (Barcelona only)

Domestic club league — no FIFA ranking applicable.  Upset criterion uses
La Liga final table positions (2020/21 season ending position).
Barcelona matches where they lost to a team ranked >= 10 places below them
in the table are classified as upsets.

Source: Google AI overview / Claude (hardcoded — no Wikipedia FIFA ranking table).

In [123]:
# ── Section 4: La Liga 2020/21 — Barcelona ────────────────────────────────────
# Hardcoded from Google AI overview / Claude.
# La Liga 2020/21 final standings (position used as proxy for 'rank'):
#   1 Atlético Madrid, 2 Real Madrid, 3 Barcelona, 4 Sevilla, 5 Real Sociedad,
#   6 Real Betis, 7 Villarreal, 8 Celta Vigo, 9 Granada, 10 Athletic Bilbao,
#   11 Osasuna, 12 Cádiz, 13 Valencia, 14 Valladolid, 15 Huesca,
#   16 Elche, 17 Getafe, 18 Deportivo Alavés, 19 Eibar, 20 SD Huesca
#
# Barcelona (rank 3) match where they lost to Granada (rank 9) on 2021-04-29.
# Rank difference = 9 - 3 = 6 < 10 → does NOT meet threshold.
# (No Barcelona upset qualifies under the >= 10-position threshold in 20/21.)

laliga_rank_map = {
    "Atlético Madrid": 1, "Real Madrid": 2, "Barcelona": 3, "Sevilla": 4,
    "Real Sociedad": 5, "Real Betis": 6, "Villarreal": 7, "Celta Vigo": 8,
    "Granada": 9, "Athletic Bilbao": 10, "Osasuna": 11, "Cádiz": 12,
    "Valencia": 13, "Valladolid": 14, "Levante": 15, "Getafe": 16,
    "Elche": 17, "Deportivo Alavés": 18, "Eibar": 19, "SD Huesca": 20,
}

# Barcelona's 2020/21 matches (losses and draws — all others were wins):
# Source: hardcoded from AI overview
barcelona_matches = [
    {"home": "Barcelona", "away": "Granada",         "home_score": 1, "away_score": 2, "date": "2021-04-29"},
    {"home": "Real Madrid", "away": "Barcelona",     "home_score": 3, "away_score": 1, "date": "2020-10-24"},
    {"home": "Cádiz", "away": "Barcelona",           "home_score": 2, "away_score": 1, "date": "2020-12-05"},
    {"home": "Barcelona", "away": "Atlético Madrid", "home_score": 0, "away_score": 1, "date": "2021-05-08"},
]

laliga_upsets = identify_upsets_from_matches(
    barcelona_matches, laliga_rank_map, RANK_DIFF_THRESHOLD
)
print(f"La Liga 20/21 Barcelona upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(laliga_upsets)}")
display(laliga_upsets)
print("Note: Cádiz (rank 12) beat Barcelona (rank 3) → diff = 9, just below threshold.")
print("Reduce RANK_DIFF_THRESHOLD to 9 to include Cádiz vs Barcelona.")

La Liga 20/21 Barcelona upsets (rank diff >= 8): 1

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,2020-12-05,Cádiz,Barcelona,2-1,Barcelona,Cádiz,3,12,9

Note: Cádiz (rank 12) beat Barcelona (rank 3) → diff = 9, just below threshold.
Reduce RANK_DIFF_THRESHOLD to 9 to include Cádiz vs Barcelona.

In [124]:
# -- Section 4: La Liga 2020/21 -- Barcelona -----------------------------------
# Hardcoded from Google AI overview / Claude.
# La Liga 2020/21 final standings (position used as rank proxy):
#   1 Atletico Madrid, 2 Real Madrid, 3 Barcelona, 4 Sevilla, 5 Real Sociedad,
#   6 Real Betis, 7 Villarreal, 8 Celta Vigo, 9 Granada, 10 Athletic Bilbao,
#   11 Osasuna, 12 Cadiz, 13 Valencia, 14 Valladolid, 15 Levante, 16 Getafe,
#   17 Elche, 18 Deportivo Alaves, 19 Eibar, 20 SD Huesca
#
# Control = Barcelona (rank 3) beating a team ranked >= 13 (diff >= 10).

laliga_rank_map = {
    "Atletico Madrid": 1, "Real Madrid": 2, "Barcelona": 3, "Sevilla": 4,
    "Real Sociedad": 5, "Real Betis": 6, "Villarreal": 7, "Celta Vigo": 8,
    "Granada": 9, "Athletic Bilbao": 10, "Osasuna": 11, "Cadiz": 12,
    "Valencia": 13, "Valladolid": 14, "Levante": 15, "Getafe": 16,
    "Elche": 17, "Deportivo Alaves": 18, "Eibar": 19, "SD Huesca": 20,
}

# Barcelona wins over much-lower-placed sides (AI-sourced hardcoded):
barcelona_matches = [
    {"home": "Barcelona", "away": "Elche",       "home_score": 3, "away_score": 0, "date": "2021-02-24"},
    {"home": "Getafe",    "away": "Barcelona",    "home_score": 0, "away_score": 1, "date": "2021-04-22"},
    {"home": "Barcelona", "away": "Valladolid",   "home_score": 1, "away_score": 0, "date": "2021-04-05"},
    {"home": "Barcelona", "away": "SD Huesca",    "home_score": 4, "away_score": 1, "date": "2021-03-15"},
    {"home": "Eibar",     "away": "Barcelona",    "home_score": 0, "away_score": 1, "date": "2021-05-22"},
    {"home": "Barcelona", "away": "Granada",      "home_score": 1, "away_score": 2, "date": "2021-04-29"},  # upset, not control
]

laliga_controls = identify_controls_from_matches(
    barcelona_matches, laliga_rank_map, RANK_DIFF_THRESHOLD
)
print(f"La Liga 20/21 Barcelona controls (rank diff >= {RANK_DIFF_THRESHOLD}): {len(laliga_controls)}")
display(laliga_controls)
print("Note: Barcelona 1-2 Granada (diff 6) is an UPSET and below threshold; excluded here.")

La Liga 20/21 Barcelona controls (rank diff >= 8): 5

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,2021-02-24,Barcelona,Elche,3-0,Barcelona,Elche,3,17,14
1,2021-04-22,Getafe,Barcelona,0-1,Barcelona,Getafe,3,16,13
2,2021-04-05,Barcelona,Valladolid,1-0,Barcelona,Valladolid,3,14,11
3,2021-03-15,Barcelona,SD Huesca,4-1,Barcelona,SD Huesca,3,20,17
4,2021-05-22,Eibar,Barcelona,0-1,Barcelona,Eibar,3,19,16

Note: Barcelona 1-2 Granada (diff 6) is an UPSET and below threshold; excluded here.

---
## Section 5 — Ligue 1 2022/23 (PSG only)

Domestic club league — no FIFA ranking applicable.  Upset criterion uses
Ligue 1 2022/23 final standings.  Source: AI overview / Claude (hardcoded).

In [125]:
# ── Section 5: Ligue 1 2022/23 — PSG ─────────────────────────────────────────
# Hardcoded from Google AI overview / Claude.
# Ligue 1 2022/23 final standings (approximate positions):
#   1 PSG, 2 Lens, 3 Marseille, 4 Rennes, 5 Lille, 6 Monaco, 7 Lyon,
#   8 Nice, 9 Montpellier, 10 Lorient, 11 Toulouse, 12 Reims, 13 Nantes,
#   14 Brest, 15 Strasbourg, 16 Clermont, 17 Troyes, 18 Ajaccio
#
# PSG dropped points in 2022/23:
# - Lost 0-1 vs Monaco (rank 6) on 2022-11-12 → diff = 5 < 10
# - Lost 2-3 vs Rennes  (rank 4) on 2023-01-15 → diff = 3 < 10
# No PSG loss meets the >= 10-position threshold in 2022/23.

ligue1_2223_rank_map = {
    "PSG": 1, "Lens": 2, "Marseille": 3, "Rennes": 4, "Lille": 5,
    "Monaco": 6, "Lyon": 7, "Nice": 8, "Montpellier": 9, "Lorient": 10,
    "Toulouse": 11, "Reims": 12, "Nantes": 13, "Brest": 14,
    "Strasbourg": 15, "Clermont": 16, "Troyes": 17, "Ajaccio": 18,
}

psg_2223_matches = [
    {"home": "Monaco",     "away": "PSG",    "home_score": 1, "away_score": 0, "date": "2022-11-12"},
    {"home": "Rennes",     "away": "PSG",    "home_score": 1, "away_score": 0, "date": "2023-01-15"},
    {"home": "PSG",        "away": "Lens",   "home_score": 1, "away_score": 1, "date": "2023-01-01"},
]

ligue1_2223_upsets = identify_upsets_from_matches(
    psg_2223_matches, ligue1_2223_rank_map, RANK_DIFF_THRESHOLD
)
print(f"Ligue 1 22/23 PSG upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(ligue1_2223_upsets)}")
display(ligue1_2223_upsets)

Ligue 1 22/23 PSG upsets (rank diff >= 8): 0

Empty DataFrame
Columns: []
Index: []

In [126]:
# -- Section 5: Ligue 1 2022/23 -- PSG -----------------------------------------

ligue1_2223_rank_map = {
    "PSG": 1, "Lens": 2, "Marseille": 3, "Rennes": 4, "Lille": 5,
    "Monaco": 6, "Lyon": 7, "Nice": 8, "Montpellier": 9, "Lorient": 10,
    "Toulouse": 11, "Reims": 12, "Nantes": 13, "Brest": 14,
    "Strasbourg": 15, "Clermont": 16, "Troyes": 17, "Ajaccio": 18,
}

psg_2223_matches = [
    {"home": "PSG",     "away": "Ajaccio",  "home_score": 5, "away_score": 0, "date": "2022-10-15"},
    {"home": "Troyes",  "away": "PSG",      "home_score": 1, "away_score": 3, "date": "2022-10-29"},
    {"home": "PSG",     "away": "Brest",    "home_score": 2, "away_score": 1, "date": "2023-01-01"},
    {"home": "PSG",     "away": "Toulouse", "home_score": 2, "away_score": 1, "date": "2023-02-04"},
    {"home": "Reims",   "away": "PSG",      "home_score": 1, "away_score": 1, "date": "2023-01-29"},  # draw, not control
]

ligue1_2223_controls = identify_controls_from_matches(
    psg_2223_matches, ligue1_2223_rank_map, RANK_DIFF_THRESHOLD
)
print(f"Ligue 1 22/23 PSG controls (rank diff >= {RANK_DIFF_THRESHOLD}): {len(ligue1_2223_controls)}")
display(ligue1_2223_controls)

Ligue 1 22/23 PSG controls (rank diff >= 8): 4

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,2022-10-15,PSG,Ajaccio,5-0,PSG,Ajaccio,1,18,17
1,2022-10-29,Troyes,PSG,1-3,PSG,Troyes,1,17,16
2,2023-01-01,PSG,Brest,2-1,PSG,Brest,1,14,13
3,2023-02-04,PSG,Toulouse,2-1,PSG,Toulouse,1,11,10

---
## Section 6 — Ligue 1 2021/22 (PSG only)

Source: AI overview / Claude (hardcoded).

In [127]:
# ── Section 6: Ligue 1 2021/22 — PSG ─────────────────────────────────────────

ligue1_2122_rank_map = {
    "PSG": 1, "Marseille": 2, "Monaco": 3, "Rennes": 4, "Strasbourg": 5,
    "Nice": 6, "Nantes": 7, "Lens": 8, "Lyon": 9, "Montpellier": 10,
    "Brest": 11, "Lille": 12, "Lorient": 13, "Clermont": 14, "Troyes": 15,
    "Reims": 16, "Saint-Étienne": 17, "Bordeaux": 18,
}

psg_2122_matches = [
    {"home": "Monaco", "away": "PSG",    "home_score": 1, "away_score": 0, "date": "2021-11-21"},
    {"home": "Nice",   "away": "PSG",    "home_score": 2, "away_score": 1, "date": "2022-03-05"},
    {"home": "PSG",    "away": "Lens",   "home_score": 1, "away_score": 1, "date": "2021-09-10"},
]

ligue1_2122_upsets = identify_upsets_from_matches(
    psg_2122_matches, ligue1_2122_rank_map, RANK_DIFF_THRESHOLD
)
print(f"Ligue 1 21/22 PSG upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(ligue1_2122_upsets)}")
display(ligue1_2122_upsets)

Ligue 1 21/22 PSG upsets (rank diff >= 8): 0

Empty DataFrame
Columns: []
Index: []

In [128]:
# -- Section 6: Ligue 1 2021/22 -- PSG -----------------------------------------

ligue1_2122_rank_map = {
    "PSG": 1, "Marseille": 2, "Monaco": 3, "Rennes": 4, "Strasbourg": 5,
    "Nice": 6, "Nantes": 7, "Lens": 8, "Lyon": 9, "Montpellier": 10,
    "Brest": 11, "Lille": 12, "Lorient": 13, "Clermont": 14, "Troyes": 15,
    "Reims": 16, "Saint-Etienne": 17, "Bordeaux": 18,
}

psg_2122_matches = [
    {"home": "PSG",            "away": "Bordeaux",       "home_score": 3, "away_score": 0, "date": "2022-03-13"},
    {"home": "Saint-Etienne",  "away": "PSG",            "home_score": 1, "away_score": 3, "date": "2021-11-28"},
    {"home": "PSG",            "away": "Reims",          "home_score": 2, "away_score": 0, "date": "2021-08-29"},
    {"home": "PSG",            "away": "Clermont",       "home_score": 4, "away_score": 0, "date": "2022-04-09"},
    {"home": "PSG",            "away": "Troyes",         "home_score": 2, "away_score": 2, "date": "2022-05-08"},  # draw, not control
]

ligue1_2122_controls = identify_controls_from_matches(
    psg_2122_matches, ligue1_2122_rank_map, RANK_DIFF_THRESHOLD
)
print(f"Ligue 1 21/22 PSG controls (rank diff >= {RANK_DIFF_THRESHOLD}): {len(ligue1_2122_controls)}")
display(ligue1_2122_controls)

Ligue 1 21/22 PSG controls (rank diff >= 8): 4

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,2022-03-13,PSG,Bordeaux,3-0,PSG,Bordeaux,1,18,17
1,2021-11-28,Saint-Etienne,PSG,1-3,PSG,Saint-Etienne,1,17,16
2,2021-08-29,PSG,Reims,2-0,PSG,Reims,1,16,15
3,2022-04-09,PSG,Clermont,4-0,PSG,Clermont,1,14,13

---
## Section 7 — MLS 2023 (Inter Miami, 6 matches)

MLS uses a different ranking system (Supporters' Shield points / playoff seeds),
not FIFA rankings.  Source: AI overview / Claude (hardcoded).

In [129]:
# ── Section 7: MLS 2023 — Inter Miami (6 matches) ────────────────────────────
mls_rank_map = {
    "Inter Miami":   11,   # mid-table at time of Leagues Cup entry
    "Club América":   3,   # Liga MX rank (approximate)
    "Atlanta United": 8,
    "Nashville SC":   4,
    "FC Dallas":      7,
    "CF Montréal":    6,
}

# Inter Miami's 6 StatsBomb-tracked Leagues Cup 2023 matches:
# (Results hardcoded — AI overview / Claude)
miami_matches = [
    {"home": "Inter Miami", "away": "Club América",   "home_score": 2, "away_score": 1, "date": "2023-07-21"},
    {"home": "Inter Miami", "away": "Atlanta United", "home_score": 4, "away_score": 0, "date": "2023-07-25"},
    {"home": "Inter Miami", "away": "Nashville SC",   "home_score": 1, "away_score": 1, "date": "2023-08-02"},
    {"home": "Inter Miami", "away": "FC Dallas",      "home_score": 5, "away_score": 3, "date": "2023-08-08"},
    {"home": "Inter Miami", "away": "CF Montréal",    "home_score": 4, "away_score": 0, "date": "2023-08-12"},
    {"home": "Inter Miami", "away": "Nashville SC",   "home_score": 1, "away_score": 0, "date": "2023-08-19"},
]

mls_upsets = identify_upsets_from_matches(miami_matches, mls_rank_map, RANK_DIFF_THRESHOLD)
print(f"MLS 2023 Inter Miami upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(mls_upsets)}")
display(mls_upsets)
print("Note: Club América (rank ~3) defeated by Inter Miami (rank 11) → diff = 8 < 10.")

MLS 2023 Inter Miami upsets (rank diff >= 8): 1

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,2023-07-21,Inter Miami,Club América,2-1,Club América,Inter Miami,3,11,8

Note: Club América (rank ~3) defeated by Inter Miami (rank 11) → diff = 8 < 10.

In [130]:
# -- Section 7: MLS 2023 -- Inter Miami (6 matches) ----------------------------
mls_rank_map = {
    "Inter Miami":   11,   # mid-table at time of Leagues Cup entry
    "Club America":   3,
    "Atlanta United": 8,
    "Nashville SC":   4,
    "FC Dallas":      7,
    "CF Montreal":    6,
}

# Inter Miami's 6 StatsBomb-tracked Leagues Cup 2023 fixtures:
miami_matches = [
    {"home": "Inter Miami", "away": "Club America",   "home_score": 2, "away_score": 1, "date": "2023-07-21"},
    {"home": "Inter Miami", "away": "Atlanta United", "home_score": 4, "away_score": 0, "date": "2023-07-25"},
    {"home": "Inter Miami", "away": "Nashville SC",   "home_score": 1, "away_score": 1, "date": "2023-08-02"},
    {"home": "Inter Miami", "away": "FC Dallas",      "home_score": 5, "away_score": 3, "date": "2023-08-08"},
    {"home": "Inter Miami", "away": "CF Montreal",    "home_score": 4, "away_score": 0, "date": "2023-08-12"},
    {"home": "Inter Miami", "away": "Nashville SC",   "home_score": 1, "away_score": 0, "date": "2023-08-19"},
]

mls_controls = identify_controls_from_matches(miami_matches, mls_rank_map, RANK_DIFF_THRESHOLD)
print(f"MLS 2023 Inter Miami controls (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(mls_controls)}")
display(mls_controls)
print("Note: all 6 fixtures have rank diff < 10 (Inter Miami 11 vs Club America 3 = 8),")
print("      so none qualify as control under the threshold; Inter Miami (underdog) also won most.")

MLS 2023 Inter Miami controls (favourite won, rank diff >= 8): 0

Empty DataFrame
Columns: []
Index: []

Note: all 6 fixtures have rank diff < 10 (Inter Miami 11 vs Club America 3 = 8),
      so none qualify as control under the threshold; Inter Miami (underdog) also won most.

---
## Section 8 — UEFA Euro 2024

Wikipedia main article: [UEFA Euro 2024](https://en.wikipedia.org/wiki/UEFA_Euro_2024)

Sub-pages: Group A–F and knockout stage (round of 16, quarter-finals, semi-finals, final).
FIFA rankings used are those published before the tournament (March 2024).

In [131]:
# ── Section 8: UEFA Euro 2024 ─────────────────────────────────────────────────
EURO2024_MAIN = "https://en.wikipedia.org/wiki/UEFA_Euro_2024"

soup_e24 = fetch_soup(EURO2024_MAIN)
e24_links = find_main_article_links(soup_e24)
print("UEFA Euro 2024 sub-pages:", len(e24_links))
for lnk in e24_links:
    print(" ", lnk)

UEFA Euro 2024 sub-pages: 19
  https://en.wikipedia.org/wiki/2024_European_Men%27s_Handball_Championship
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_bids
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_qualifying
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_squads
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_A
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_B
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_C
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_D
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_E
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_F
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_knockout_stage
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_final
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_statistics
  https://en.wikipedia.org/wiki/UEFA_European_Championship_awards
  https://en.wikipedia.org/wiki/UEFA_European_Championship_records_and_statistics
  https://en.wikipedia.org/wiki/UEFA_European_Championship_video_games#UEFA_Euro_2024
  https://en.wikipedia.org/wiki/Fire_(Meduza,_OneRepublic_and_Leony_song)
  https://en.wikipedia.org/wiki/UEFA_Euro_2024_broadcasting_rights
  https://en.wikipedia.org/wiki/Top_Coffee_bombing

In [132]:
# Filter to group (A–F) and knockout stage
euro2024_stage_pattern = re.compile(
    r"UEFA_Euro_2024_(Group_[A-F]|knockout_stage|round_of_16|quarter-finals|semi-finals|Final)$",
    re.IGNORECASE
)

e24_stage_links = [lnk for lnk in e24_links if euro2024_stage_pattern.search(lnk)]
print("Filtered stage pages:", e24_stage_links)

e24_rank_map = {}
e24_matches  = []

for link in e24_stage_links:
    try:
        gsoup = fetch_soup(link)
        rank_df = extract_rank_table(gsoup)
        if rank_df is not None:
            for _, row in rank_df.iterrows():
                e24_rank_map[row["team"]] = row["fifa_rank"]
        e24_matches.extend(parse_match_results_from_soup(gsoup))
    except Exception as ex:
        print(f"  Error: {ex}")

print(f"Euro 2024 rank map: {len(e24_rank_map)} teams")
print(f"Euro 2024 matches found: {len(e24_matches)}")

Filtered stage pages: ['https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_A', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_B', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_C', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_D', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_E', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_Group_F', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_knockout_stage', 'https://en.wikipedia.org/wiki/UEFA_Euro_2024_final']
Euro 2024 rank map: 24 teams
Euro 2024 matches found: 52

In [133]:
e24_upsets = identify_upsets_from_matches(e24_matches, e24_rank_map, RANK_DIFF_THRESHOLD)
print(f"Euro 2024 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(e24_upsets)}")
display(e24_upsets)

# Validate key games are captured:
# Expected upsets (cross-checking with xG-based results):
#   Netherlands 2-3 Austria, Georgia 2-0 Portugal,
#   Slovakia 1-0 Belgium, Romania 3-0 Ukraine
expected = [
    ("Netherlands", "Austria"),
    ("Georgia", "Portugal"),
    ("Slovakia", "Belgium"),
    ("Romania", "Ukraine"),
]
if not e24_upsets.empty:
    for fav, und in expected:
        found = ((e24_upsets["favourite"] == fav) & (e24_upsets["underdog"] == und)).any()
        print(f"  {und} beat {fav}: {'FOUND' if found else 'MISSING'} in upset list")

Euro 2024 upsets (rank diff >= 8): 6

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Netherlands,Austria,2-3,Netherlands,Austria,7,25,18
1,,Romania,Ukraine,3-0,Ukraine,Romania,22,46,24
2,,Belgium,Slovakia,0-1,Belgium,Slovakia,3,48,45
3,,Georgia,Portugal,2-0,Portugal,Georgia,6,75,69
4,,Switzerland,Italy,2-0,Italy,Switzerland,9,19,10
5,,Austria,Turkey,1-2,Austria,Turkey,25,40,15

  Austria beat Netherlands: FOUND in upset list
  Portugal beat Georgia: MISSING in upset list
  Belgium beat Slovakia: MISSING in upset list
  Ukraine beat Romania: MISSING in upset list

In [134]:
e24_controls = identify_controls_from_matches(e24_matches, e24_rank_map, RANK_DIFF_THRESHOLD)
print(f"Euro 2024 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(e24_controls)}")
display(e24_controls)

Euro 2024 control matches (favourite won, rank diff >= 8): 18

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Germany,Scotland,5-1,Germany,Scotland,16,39,23
1,,Germany,Hungary,2-0,Germany,Hungary,16,26,10
2,,Scotland,Hungary,0-1,Hungary,Scotland,26,39,13
3,,Italy,Albania,2-1,Italy,Albania,9,66,57
4,,Albania,Spain,0-1,Spain,Albania,8,66,58
5,,Serbia,England,0-1,England,Serbia,4,33,29
6,,Poland,Netherlands,1-2,Netherlands,Poland,7,28,21
7,,Austria,France,0-1,France,Austria,2,25,23
8,,Slovakia,Ukraine,1-2,Ukraine,Slovakia,22,48,26
9,,Belgium,Romania,2-0,Belgium,Romania,3,46,43
10,,Turkey,Georgia,3-1,Turkey,Georgia,40,75,35
11,,Portugal,Czech Republic,2-1,Portugal,Czech Republic,6,36,30
12,,Turkey,Portugal,0-3,Portugal,Turkey,6,40,34
13,,England,Slovakia,2-1,England,Slovakia,4,48,44
14,,Spain,Georgia,4-1,Spain,Georgia,8,75,67
15,,Romania,Netherlands,0-3,Netherlands,Romania,7,46,39
16,,Spain,Germany,2-1,Spain,Germany,8,16,8
17,,Netherlands,Turkey,2-1,Netherlands,Turkey,7,40,33

---
## Section 9 — UEFA Euro 2020 (held 2021)

Wikipedia main article: [UEFA Euro 2020](https://en.wikipedia.org/wiki/UEFA_Euro_2020)

In [135]:
# ── Section 9: UEFA Euro 2020 ─────────────────────────────────────────────────
EURO2020_MAIN = "https://en.wikipedia.org/wiki/UEFA_Euro_2020"

soup_e20 = fetch_soup(EURO2020_MAIN)
e20_links = find_main_article_links(soup_e20)

euro2020_stage_pattern = re.compile(
    r"UEFA_Euro_2020_(Group_[A-F]|knockout_stage|round_of_16|quarter-finals|semi-finals|Final)$",
    re.IGNORECASE
)
e20_stage_links = [lnk for lnk in e20_links if euro2020_stage_pattern.search(lnk)]
print("Euro 2020 stage pages:", e20_stage_links)

e20_rank_map = {}
e20_matches  = []

for link in e20_stage_links:
    try:
        gsoup = fetch_soup(link)
        rank_df = extract_rank_table(gsoup)
        if rank_df is not None:
            for _, row in rank_df.iterrows():
                e20_rank_map[row["team"]] = row["fifa_rank"]
        e20_matches.extend(parse_match_results_from_soup(gsoup))
    except Exception as ex:
        print(f"  Error: {ex}")

e20_upsets = identify_upsets_from_matches(e20_matches, e20_rank_map, RANK_DIFF_THRESHOLD)
print(f"Euro 2020 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(e20_upsets)}")
display(e20_upsets)

Euro 2020 stage pages: ['https://en.wikipedia.org/wiki/UEFA_Euro_2020_Group_A', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_Group_B', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_Group_C', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_Group_D', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_Group_E', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_Group_F', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_knockout_stage', 'https://en.wikipedia.org/wiki/UEFA_Euro_2020_final']
Euro 2020 upsets (rank diff >= 8): 1

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Poland,Slovakia,1-2,Poland,Slovakia,21,36,15

In [136]:
e20_controls = identify_controls_from_matches(e20_matches, e20_rank_map, RANK_DIFF_THRESHOLD)
print(f"Euro 2020 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(e20_controls)}")
display(e20_controls)

Euro 2020 control matches (favourite won, rank diff >= 8): 6

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Turkey,Wales,0-2,Wales,Turkey,17,29,12
1,,Switzerland,Turkey,3-1,Switzerland,Turkey,13,29,16
2,,Finland,Belgium,0-2,Belgium,Finland,1,54,53
3,,Austria,North Macedonia,3-1,Austria,North Macedonia,23,62,39
4,,Ukraine,North Macedonia,2-1,Ukraine,North Macedonia,24,62,38
5,,Sweden,Slovakia,1-0,Sweden,Slovakia,18,36,18

---
## Section 10 — UEFA Women's Euro 2025

Wikipedia main article: [UEFA Women's Euro 2025](https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025)

In [137]:
# ── Section 10: UEFA Women's Euro 2025 ───────────────────────────────────────
WEURO2025_MAIN = "https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025"

try:
    soup_we25 = fetch_soup(WEURO2025_MAIN)
    we25_links = find_main_article_links(soup_we25)
    we25_stage_pattern = re.compile(
        r"UEFA_Women[^/]*Euro_2025_(Group_[A-D]|knockout_stage|quarter-finals|semi-finals|final)$",
        re.IGNORECASE
    )
    we25_stage_links = [lnk for lnk in we25_links if we25_stage_pattern.search(lnk)]
    print("Women's Euro 2025 stage pages:", we25_stage_links)

    we25_rank_map = {}
    we25_matches  = []

    for link in we25_stage_links:
        try:
            gsoup = fetch_soup(link)
            rank_df = extract_rank_table(gsoup)
            if rank_df is not None:
                for _, row in rank_df.iterrows():
                    we25_rank_map[row["team"]] = row["fifa_rank"]
            we25_matches.extend(parse_match_results_from_soup(gsoup))
        except Exception as ex:
            print(f"  Error: {ex}")

    we25_upsets = identify_upsets_from_matches(we25_matches, we25_rank_map, RANK_DIFF_THRESHOLD)
    print(f"Women's Euro 2025 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(we25_upsets)}")
    display(we25_upsets)

except Exception as e:
    print(f"Women's Euro 2025 scraping failed (may not be fully available yet): {e}")

Women's Euro 2025 stage pages: ['https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025_Group_A', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025_Group_B', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025_Group_C', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025_Group_D', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025_knockout_stage', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2025_final']
Women's Euro 2025 upsets (rank diff >= 8): 3

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Iceland,Finland,0-1,Iceland,Finland,14,26,12
1,,Switzerland,Iceland,2-0,Iceland,Switzerland,14,23,9
2,,Poland,Denmark,3-2,Denmark,Poland,12,28,16

In [138]:
if 'we25_matches' in dir() and 'we25_rank_map' in dir():
    we25_controls = identify_controls_from_matches(we25_matches, we25_rank_map, RANK_DIFF_THRESHOLD)
    print(f"Women's Euro 2025 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(we25_controls)}")
    display(we25_controls)
else:
    print("Women's Euro 2025 data unavailable; no control matches computed.")

Women's Euro 2025 control matches (favourite won, rank diff >= 8): 12

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Norway,Finland,2-1,Norway,Finland,16,26,10
1,,Spain,Portugal,5-0,Spain,Portugal,2,22,20
2,,Spain,Belgium,6-2,Spain,Belgium,2,19,17
3,,Italy,Spain,1-3,Spain,Italy,2,13,11
4,,Germany,Poland,2-0,Germany,Poland,3,28,25
5,,Germany,Denmark,2-1,Germany,Denmark,3,12,9
6,,Poland,Sweden,0-3,Sweden,Poland,5,28,23
7,,Wales,Netherlands,0-3,Netherlands,Wales,10,30,20
8,,France,Wales,4-1,France,Wales,11,30,19
9,,England,Wales,6-1,England,Wales,4,30,26
10,,Spain,Switzerland,2-0,Spain,Switzerland,2,23,21
11,,England,Italy,2-1,England,Italy,4,13,9

---
## Section 11 — UEFA Women's Euro 2022

Wikipedia main article: [UEFA Women's Euro 2022](https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022)

In [139]:
# ── Section 11: UEFA Women's Euro 2022 ───────────────────────────────────────
WEURO2022_MAIN = "https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022"

soup_we22 = fetch_soup(WEURO2022_MAIN)
we22_links = find_main_article_links(soup_we22)
we22_stage_pattern = re.compile(
    r"UEFA_Women[^/]*Euro_2022_(Group_[A-D]|knockout_stage|quarter-finals|semi-finals|final)$",
    re.IGNORECASE
)
we22_stage_links = [lnk for lnk in we22_links if we22_stage_pattern.search(lnk)]
print("Women's Euro 2022 stage pages:", we22_stage_links)

we22_rank_map = {}
we22_matches  = []

for link in we22_stage_links:
    try:
        gsoup = fetch_soup(link)
        rank_df = extract_rank_table(gsoup)
        if rank_df is not None:
            for _, row in rank_df.iterrows():
                we22_rank_map[row["team"]] = row["fifa_rank"]
        we22_matches.extend(parse_match_results_from_soup(gsoup))
    except Exception as ex:
        print(f"  Error: {ex}")

we22_upsets = identify_upsets_from_matches(we22_matches, we22_rank_map, RANK_DIFF_THRESHOLD)
print(f"Women's Euro 2022 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(we22_upsets)}")
display(we22_upsets)

Women's Euro 2022 stage pages: ['https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022_Group_A', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022_Group_B', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022_Group_C', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022_Group_D', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022_knockout_stage', 'https://en.wikipedia.org/wiki/UEFA_Women%27s_Euro_2022_final']
Women's Euro 2022 upsets (rank diff >= 8): 1

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Austria,Norway,1-0,Norway,Austria,11,21,10

In [140]:
we22_controls = identify_controls_from_matches(we22_matches, we22_rank_map, RANK_DIFF_THRESHOLD)
print(f"Women's Euro 2022 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(we22_controls)}")
display(we22_controls)

Women's Euro 2022 control matches (favourite won, rank diff >= 8): 17

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,England,Austria,1-0,England,Austria,8,21,13
1,,Norway,Northern Ireland,4-1,Norway,Northern Ireland,11,47,36
2,,Austria,Northern Ireland,2-0,Austria,Northern Ireland,21,47,26
3,,Northern Ireland,England,0-5,England,Northern Ireland,8,47,39
4,,Spain,Finland,4-1,Spain,Finland,7,29,22
5,,Germany,Denmark,4-0,Germany,Denmark,5,15,10
6,,Denmark,Finland,1-0,Denmark,Finland,15,29,14
7,,Finland,Germany,0-3,Germany,Finland,5,29,24
8,,Denmark,Spain,0-1,Spain,Denmark,7,15,8
9,,Sweden,Switzerland,2-1,Sweden,Switzerland,2,20,18
10,,Netherlands,Portugal,3-2,Netherlands,Portugal,4,30,26
11,,Switzerland,Netherlands,1-4,Netherlands,Switzerland,4,20,16
12,,Sweden,Portugal,5-0,Sweden,Portugal,2,30,28
13,,France,Italy,5-1,France,Italy,3,14,11
14,,France,Belgium,2-1,France,Belgium,3,19,16
15,,Germany,Austria,2-0,Germany,Austria,5,21,16
16,,Sweden,Belgium,1-0,Sweden,Belgium,2,19,17

---
## Section 12 — FIFA Women's World Cup 2023

Wikipedia main article: [2023 FIFA Women's World Cup](https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup)

In [141]:
# ── Section 12: FIFA Women's World Cup 2023 ───────────────────────────────────
WWC2023_MAIN = "https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup"

soup_wwc = fetch_soup(WWC2023_MAIN)
wwc_links = find_main_article_links(soup_wwc)

wwc_stage_pattern = re.compile(
    r"2023_FIFA_Women[^/]*World_Cup_(Group_[A-H]|knockout_stage|final)$",
    re.IGNORECASE
)
wwc_stage_links = [lnk for lnk in wwc_links if wwc_stage_pattern.search(lnk)]
print("WWC 2023 stage pages:", wwc_stage_links)

wwc_rank_map = {}
wwc_matches  = []

for link in wwc_stage_links:
    try:
        gsoup = fetch_soup(link)
        rank_df = extract_rank_table(gsoup)
        if rank_df is not None:
            for _, row in rank_df.iterrows():
                wwc_rank_map[row["team"]] = row["fifa_rank"]
        wwc_matches.extend(parse_match_results_from_soup(gsoup))
    except Exception as ex:
        print(f"  Error: {ex}")

wwc_upsets = identify_upsets_from_matches(wwc_matches, wwc_rank_map, RANK_DIFF_THRESHOLD)
print(f"WWC 2023 upsets (rank diff >= {RANK_DIFF_THRESHOLD}): {len(wwc_upsets)}")
display(wwc_upsets)

WWC 2023 stage pages: ['https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_A', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_B', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_C', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_D', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_E', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_F', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_G', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_Group_H', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_knockout_stage', 'https://en.wikipedia.org/wiki/2023_FIFA_Women%27s_World_Cup_final']
WWC 2023 upsets (rank diff >= 8): 9

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,New Zealand,Norway,1-0,Norway,New Zealand,12,26,14
1,,New Zealand,Philippines,0-1,New Zealand,Philippines,26,46,20
2,,Australia,Nigeria,2-3,Australia,Nigeria,10,40,30
3,,Costa Rica,Zambia,1-3,Costa Rica,Zambia,36,77,41
4,,South Africa,Italy,3-2,Italy,South Africa,16,54,38
5,,Colombia,South Korea,2-0,South Korea,Colombia,17,25,8
6,,South Korea,Morocco,0-1,South Korea,Morocco,17,72,55
7,,Germany,Colombia,1-2,Germany,Colombia,2,25,23
8,,Morocco,Colombia,1-0,Colombia,Morocco,25,72,47

In [142]:
wwc_controls = identify_controls_from_matches(wwc_matches, wwc_rank_map, RANK_DIFF_THRESHOLD)
print(f"WWC 2023 control matches (favourite won, rank diff >= {RANK_DIFF_THRESHOLD}): {len(wwc_controls)}")
display(wwc_controls)

WWC 2023 control matches (favourite won, rank diff >= 8): 31

,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,,Philippines,Switzerland,0-2,Switzerland,Philippines,20,46,26
1,,Norway,Philippines,6-0,Norway,Philippines,12,46,34
2,,Australia,Republic of Ireland,1-0,Australia,Republic of Ireland,10,22,12
3,,Canada,Republic of Ireland,2-1,Canada,Republic of Ireland,7,22,15
4,,Spain,Costa Rica,3-0,Spain,Costa Rica,6,36,30
5,,Zambia,Japan,0-5,Japan,Zambia,11,77,66
6,,Japan,Costa Rica,2-0,Japan,Costa Rica,11,36,25
7,,Spain,Zambia,5-0,Spain,Zambia,6,77,71
8,,England,Haiti,1-0,England,Haiti,4,53,49
9,,England,Denmark,1-0,England,Denmark,4,13,9
10,,China,Haiti,1-0,China,Haiti,14,53,39
11,,China,England,1-6,England,China,4,14,10
12,,Haiti,Denmark,0-2,Denmark,Haiti,13,53,40
13,,United States,Vietnam,3-0,United States,Vietnam,1,32,31
14,,Netherlands,Portugal,1-0,Netherlands,Portugal,9,21,12
15,,Portugal,Vietnam,2-0,Portugal,Vietnam,21,32,11
16,,Vietnam,Netherlands,0-7,Netherlands,Vietnam,9,32,23
17,,Brazil,Panama,4-0,Brazil,Panama,8,52,44
18,,Panama,Jamaica,0-1,Jamaica,Panama,43,52,9
19,,Panama,France,3-6,France,Panama,5,52,47
20,,Sweden,South Africa,2-1,Sweden,South Africa,3,54,51
21,,Italy,Argentina,1-0,Italy,Argentina,16,28,12
22,,Sweden,Italy,5-0,Sweden,Italy,3,16,13
23,,Argentina,Sweden,0-2,Sweden,Argentina,3,28,25
24,,Germany,Morocco,6-0,Germany,Morocco,2,72,70
25,,Switzerland,Spain,1-5,Spain,Switzerland,6,20,14
26,,Netherlands,South Africa,2-0,Netherlands,South Africa,9,54,45
27,,Colombia,Jamaica,1-0,Colombia,Jamaica,25,43,18
28,,France,Morocco,4-0,France,Morocco,5,72,67
29,,Japan,Sweden,1-2,Sweden,Japan,3,11,8
30,,England,Colombia,2-1,England,Colombia,4,25,21

---
## Summary: All upsets across competitions

In [143]:
# ── Summary table ─────────────────────────────────────────────────────────────
summary_rows = [
    ("Bundesliga 23/24 (Leverkusen)",      0,                                    "league — no FIFA rank"),
    ("AFCON 2023",                          len(afcon_upsets),                    "Wikipedia scraped"),
    ("FIFA WC 2022",                        len(wc_upsets),                       "Wikipedia scraped"),
    ("La Liga 20/21 (Barcelona)",           len(laliga_upsets),                   "AI-sourced hardcoded"),
    ("Ligue 1 22/23 (PSG)",                len(ligue1_2223_upsets),              "AI-sourced hardcoded"),
    ("Ligue 1 21/22 (PSG)",                len(ligue1_2122_upsets),              "AI-sourced hardcoded"),
    ("MLS 2023 (Inter Miami)",             len(mls_upsets),                       "AI-sourced hardcoded"),
    ("UEFA Euro 2024",                      len(e24_upsets),                       "Wikipedia scraped"),
    ("UEFA Euro 2020",                      len(e20_upsets),                       "Wikipedia scraped"),
    ("UEFA Women's Euro 2025",             len(we25_upsets) if 'we25_upsets' in dir() else "N/A", "Wikipedia scraped"),
    ("UEFA Women's Euro 2022",             len(we22_upsets),                      "Wikipedia scraped"),
    ("FIFA Women's WC 2023",              len(wwc_upsets),                       "Wikipedia scraped"),
]

summary_df = pd.DataFrame(summary_rows, columns=["Competition", "Upsets", "Source"])
print(f"\nRank-diff threshold: {RANK_DIFF_THRESHOLD}")
display(summary_df)

# Combine all identified upsets into one dataframe (scraped + AI-sourced leagues)
all_upset_dfs = []
for label, df in [
    ("La Liga 20/21",    laliga_upsets),
    ("Ligue 1 22/23",    ligue1_2223_upsets),
    ("Ligue 1 21/22",    ligue1_2122_upsets),
    ("MLS 2023",         mls_upsets),
    ("AFCON 2023",       afcon_upsets),
    ("WC 2022",          wc_upsets),
    ("Euro 2024",        e24_upsets),
    ("Euro 2020",        e20_upsets),
    ("Women's Euro 2022", we22_upsets),
    ("WWC 2023",         wwc_upsets),
]:
    if isinstance(df, pd.DataFrame) and not df.empty:
        df = df.copy()
        df.insert(0, "competition", label)
        all_upset_dfs.append(df)

if 'we25_upsets' in dir() and isinstance(we25_upsets, pd.DataFrame) and not we25_upsets.empty:
    tmp = we25_upsets.copy()
    tmp.insert(0, "competition", "Women's Euro 2025")
    all_upset_dfs.append(tmp)

all_upsets_combined = (pd.concat(all_upset_dfs, ignore_index=True)
                       if all_upset_dfs else pd.DataFrame())

if not all_upsets_combined.empty:
    print(f"\nTotal Wikipedia-validated upsets: {len(all_upsets_combined)}")
    display(all_upsets_combined)
else:
    print("No upsets found (check RANK_DIFF_THRESHOLD or scraping errors).")

# ── Export to Excel: upset_list.xlsx ─────────────────────────────────────────
EXCEL_PATH = "upset_list.xlsx"
with pd.ExcelWriter(EXCEL_PATH, engine="openpyxl") as writer:
    summary_df.to_excel(writer, sheet_name="summary", index=False)
    (all_upsets_combined if not all_upsets_combined.empty
     else pd.DataFrame(columns=["competition", "date", "home", "away", "score",
                                "favourite", "underdog", "fav_rank", "und_rank",
                                "rank_diff"])
     ).to_excel(writer, sheet_name="upsets", index=False)
print(f"Exported summary + {len(all_upsets_combined)} upsets to {EXCEL_PATH}")

Rank-diff threshold: 8

                      Competition  Upsets                 Source
0   Bundesliga 23/24 (Leverkusen)       0  league — no FIFA rank
1                      AFCON 2023       7      Wikipedia scraped
2                    FIFA WC 2022      11      Wikipedia scraped
3       La Liga 20/21 (Barcelona)       1   AI-sourced hardcoded
4             Ligue 1 22/23 (PSG)       0   AI-sourced hardcoded
5             Ligue 1 21/22 (PSG)       0   AI-sourced hardcoded
6          MLS 2023 (Inter Miami)       1   AI-sourced hardcoded
7                  UEFA Euro 2024       6      Wikipedia scraped
8                  UEFA Euro 2020       1      Wikipedia scraped
9          UEFA Women's Euro 2025       3      Wikipedia scraped
10         UEFA Women's Euro 2022       1      Wikipedia scraped
11           FIFA Women's WC 2023       9      Wikipedia scraped

Total Wikipedia-validated upsets: 40

,competition,date,home,away,score,favourite,underdog,fav_rank,und_rank,rank_diff
0,La Liga 20/21,2020-12-05,Cádiz,Barcelona,2-1,Barcelona,Cádiz,3,12,9
1,MLS 2023,2023-07-21,Inter Miami,Club América,2-1,Club América,Inter Miami,3,11,8
2,AFCON 2023,,Equatorial Guinea,Ivory Coast,4-0,Ivory Coast,Equatorial Guinea,49,88,39
3,AFCON 2023,,Ghana,Cape Verde,1-2,Ghana,Cape Verde,61,73,12
4,AFCON 2023,,Mauritania,Angola,2-3,Mauritania,Angola,105,117,12
5,AFCON 2023,,Angola,Burkina Faso,2-0,Burkina Faso,Angola,58,117,59
6,AFCON 2023,,Mauritania,Algeria,1-0,Algeria,Mauritania,30,105,75
7,AFCON 2023,,Tunisia,Namibia,0-1,Tunisia,Namibia,28,115,87
8,AFCON 2023,,Morocco,South Africa,0-2,Morocco,South Africa,13,66,53
9,WC 2022,,Argentina,Saudi Arabia,1-2,Argentina,Saudi Arabia,3,51,48
10,WC 2022,,Tunisia,Australia,0-1,Tunisia,Australia,30,38,8
11,WC 2022,,Australia,Denmark,1-0,Denmark,Australia,10,38,28
12,WC 2022,,Tunisia,France,1-0,France,Tunisia,4,30,26
13,WC 2022,,Germany,Japan,1-2,Germany,Japan,11,24,13
14,WC 2022,,Japan,Spain,2-1,Spain,Japan,7,24,17
15,WC 2022,,Belgium,Morocco,0-2,Belgium,Morocco,2,22,20
16,WC 2022,,Cameroon,Brazil,1-0,Brazil,Cameroon,1,43,42
17,WC 2022,,South Korea,Ghana,2-3,South Korea,Ghana,28,61,33
18,WC 2022,,South Korea,Portugal,2-1,Portugal,South Korea,9,28,19
19,WC 2022,,Morocco,Portugal,1-0,Portugal,Morocco,9,22,13
20,Euro 2024,,Netherlands,Austria,2-3,Netherlands,Austria,7,25,18
21,Euro 2024,,Romania,Ukraine,3-0,Ukraine,Romania,22,46,24
22,Euro 2024,,Belgium,Slovakia,0-1,Belgium,Slovakia,3,48,45
23,Euro 2024,,Georgia,Portugal,2-0,Portugal,Georgia,6,75,69
24,Euro 2024,,Switzerland,Italy,2-0,Italy,Switzerland,9,19,10
25,Euro 2024,,Austria,Turkey,1-2,Austria,Turkey,25,40,15
26,Euro 2020,,Poland,Slovakia,1-2,Poland,Slovakia,21,36,15
27,Women's Euro 2022,,Austria,Norway,1-0,Norway,Austria,11,21,10
28,WWC 2023,,New Zealand,Norway,1-0,Norway,New Zealand,12,26,14
29,WWC 2023,,New Zealand,Philippines,0-1,New Zealand,Philippines,26,46,20
30,WWC 2023,,Australia,Nigeria,2-3,Australia,Nigeria,10,40,30
31,WWC 2023,,Costa Rica,Zambia,1-3,Costa Rica,Zambia,36,77,41
32,WWC 2023,,South Africa,Italy,3-2,Italy,South Africa,16,54,38
33,WWC 2023,,Colombia,South Korea,2-0,South Korea,Colombia,17,25,8
34,WWC 2023,,South Korea,Morocco,0-1,South Korea,Morocco,17,72,55
35,WWC 2023,,Germany,Colombia,1-2,Germany,Colombia,2,25,23
36,WWC 2023,,Morocco,Colombia,1-0,Colombia,Morocco,25,72,47
37,Women's Euro 2025,,Iceland,Finland,0-1,Iceland,Finland,14,26,12
38,Women's Euro 2025,,Switzerland,Iceland,2-0,Iceland,Switzerland,14,23,9
39,Women's Euro 2025,,Poland,Denmark,3-2,Denmark,Poland,12,28,16

Exported summary + 40 upsets to upset_list.xlsx

---
## Export control matches to Excel (control_lists)

In [144]:
# === Export control matches to control_lists.xlsx (sheet: control_lists) ======
# Combines the per-competition control frames produced by the control sections
# above (favourite-won fixtures) and writes them to control_lists.xlsx.

control_frames = [
    ("Bundesliga 23/24",  bundesliga_controls),
    ("La Liga 20/21",     laliga_controls),
    ("Ligue 1 22/23",     ligue1_2223_controls),
    ("Ligue 1 21/22",     ligue1_2122_controls),
    ("MLS 2023",          mls_controls),
    ("AFCON 2023",        afcon_controls),
    ("WC 2022",           wc_controls),
    ("Euro 2024",         e24_controls),
    ("Euro 2020",         e20_controls),
    ("Women's Euro 2022", we22_controls),
    ("WWC 2023",          wwc_controls),
]
if 'we25_controls' in dir() and isinstance(we25_controls, pd.DataFrame):
    control_frames.append(("Women's Euro 2025", we25_controls))

control_dfs, control_summary_rows = [], []
for label, df in control_frames:
    n = len(df) if isinstance(df, pd.DataFrame) else 0
    control_summary_rows.append((label, n))
    if isinstance(df, pd.DataFrame) and not df.empty:
        d = df.copy()
        d.insert(0, "competition", label)
        control_dfs.append(d)

control_summary_df = pd.DataFrame(control_summary_rows, columns=["Competition", "Control matches"])
all_controls_combined = (pd.concat(control_dfs, ignore_index=True) if control_dfs
                         else pd.DataFrame(columns=["competition", "date", "home", "away", "score",
                                                    "favourite", "underdog", "fav_rank", "und_rank",
                                                    "rank_diff"]))

CONTROL_EXCEL_PATH = "control_lists.xlsx"
with pd.ExcelWriter(CONTROL_EXCEL_PATH, engine="openpyxl") as writer:
    control_summary_df.to_excel(writer, sheet_name="summary", index=False)
    all_controls_combined.to_excel(writer, sheet_name="control_lists", index=False)
print(f"Exported {len(all_controls_combined)} control matches to {CONTROL_EXCEL_PATH} "
      f"(sheet 'control_lists')")
display(control_summary_df)

Exported 151 control matches to control_lists.xlsx (sheet 'control_lists')

          Competition  Control matches
0    Bundesliga 23/24                6
1       La Liga 20/21                5
2       Ligue 1 22/23                4
3       Ligue 1 21/22                4
4            MLS 2023                0
5          AFCON 2023               19
6             WC 2022               29
7           Euro 2024               18
8           Euro 2020                6
9   Women's Euro 2022               17
10           WWC 2023               31
11  Women's Euro 2025               12